name: Java CI with Gradle (No Wrapper)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle (without Wrapper)
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.9' # Install Gradle manually

      - name: Build with Gradle
        run: gradle build

      - name: Run Tests
        run: gradle test

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle (without Wrapper)
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.9' # Ensure Gradle is installed

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
